service: my-serverless-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}

plugins:
  - serverless-offline

functions:
  lambda-transaction:
    name: lambda_transaction
    handler: src/infrastructure/lambdas/handler.handler
    events:
      - http:
          path: /clients
          method: post
          cors: true