service: vehicle-service-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}
    API_GATEWAY_ID: ${env:API_GATEWAY_ID} # Agregar variable de entorno para el API Gateway ID
    STAGE: ${opt:stage, 'dev'} # Agregar variable de entorno para el stage
    IS_OFFLINE: ${opt:isOffline, 'false'}
    GOOGLE_TYPE: ${env:GOOGLE_TYPE}
    GOOGLE_PROJECT_ID: ${env:GOOGLE_PROJECT_ID}
    GOOGLE_PRIVATE_KEY_ID: ${env:GOOGLE_PRIVATE_KEY_ID}
    GOOGLE_PRIVATE_KEY: ${env:GOOGLE_PRIVATE_KEY}
    GOOGLE_CLIENT_EMAIL: ${env:GOOGLE_CLIENT_EMAIL}
    GOOGLE_CLIENT_ID: ${env:GOOGLE_CLIENT_ID}
    GOOGLE_AUTH_URI: ${env:GOOGLE_AUTH_URI}
    GOOGLE_TOKEN_URI: ${env:GOOGLE_TOKEN_URI}
    GOOGLE_AUTH_PROVIDER_CERT_URL: ${env:GOOGLE_AUTH_PROVIDER_CERT_URL}
    GOOGLE_CLIENT_CERT_URL: ${env:GOOGLE_CLIENT_CERT_URL}
    GOOGLE_UNIVERSE_DOMAIN: ${env:GOOGLE_UNIVERSE_DOMAIN}
    


plugins:
  - serverless-offline


functions:
  LambdaVehicle:
    name: LambdaVehicle-${opt:stage, 'dev'}
    handler: src/infrastructure/lambdas/handler.handler
    timeout: 90
    events:
      - http:
          path: /vehicle
          method: post
          cors: true
  
  SwaggerDocumentation:
    name: SwaggerDocumentation-${opt:stage, 'dev'}
    handler: src/infrastructure/lambdas/swaggerHandler.handler
    events:
      - http:
          path: /swagger
          method: get
          cors: true

  SwaggerUI:
    name: SwaggerUI-${opt:stage, 'dev'}
    handler: src/infrastructure/lambdas/swaggerUIHandler.handler
    events:
      - http:
          path: swagger-ui
          method: any
          cors: true