# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: carrologo
service: vehicle-service-api-prod
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    STAGE: ${opt:stage, 'dev'} # Agregar variable de entorno para el stage
    IS_OFFLINE: ${opt:isOffline, 'false'}
  apiGateway:
    binaryMediaTypes:
      - "image/jpeg"
      - "image/png"
      - "image/gif"
      - "application/octet-stream"

plugins:
  - serverless-offline

functions:
  VehicleAPI:
    name: VehicleAPI-prod-${opt:stage, 'develop'}
    handler: src/infrastructure/lambdas/handler.createVehicleHandler
    timeout: 29
    events:
      - http:
          path: /vehicle
          method: post
          cors: true
  
  listVehicles:
    name: ListVehicles-prod-${opt:stage, 'develop'}
    handler: src/infrastructure/lambdas/handler.getAllVehiclesHandler
    timeout: 29
    events:
      - http:
          path: /vehicles
          method: get
          cors: true
  
  getVehicleById:
    name: GetVehicleById-prod-${opt:stage, 'develop'}
    handler: src/infrastructure/lambdas/handler.getDetailVehicleHandler
    timeout: 29
    events:
      - http:
          path: /vehicles/{id}
          method: get
          cors: true
  
  updateVehicleById:
    name: UpdateVehicleById-prod-${opt:stage, 'develop'}
    handler: src/infrastructure/lambdas/handler.updateVehicleHandler
    timeout: 29
    events:
      - http:
          path: /vehicles/{id}
          method: patch
          cors: true

  getImage:
    name: GetImage-prod-${opt:stage, 'develop'}
    handler: src/infrastructure/lambdas/handler.getImageVehicleHandler
    timeout: 29
    events:
      - http:
          path: /image
          method: get
          cors: true
    

  listGoogleDriveFolders:
    name: ListGoogleDriveFolders-prod-${opt:stage, 'develop'}
    handler: src/infrastructure/lambdas/handler.listGoogleDriveFoldersHandler
    timeout: 29
    events:
      - http:
          path: /drive/folders
          method: get
          cors: true
  
  deleteGoogleDriveFolders:
    name: DeleteGoogleDriveFolders-prod-${opt:stage, 'develop'}
    handler: src/infrastructure/lambdas/handler.deleteGoogleDriveFoldersHandler
    timeout: 29
    events:
      - http:
          path: /drive/folders
          method: delete
          cors: true

  SwaggerDocumentation:
    name: SwaggerDocumentation-prod-${opt:stage, 'develop'}
    handler: src/infrastructure/lambdas/swaggerHandler.handler
    events:
      - http:
          path: /swagger
          method: get
          cors: true

  SwaggerUI:
    name: SwaggerUI-prod-${opt:stage, 'develop'}
    handler: src/infrastructure/lambdas/swaggerUIHandler.handler
    events:
      - http:
          path: swagger-ui
          method: any
          cors: true
